### ISSUE TITLE
College Id and Reg No. not enough for authentication of a student.

### ISSUE THREAD

**Issue by rajatsaxena035** [gargsarthak30/Result-Viewer#2]
At the time of Student _Registration_, we are asking for the following info :
**College Id** = { soict, som, sovsas, ....} = Every one knows.
**Reg. No.** =  { 13ics035, 12iec029, 15pit052, ....} = Every one knows.
**Password** = Own choice.
**Confirm Password** = Own choice (Same as Password).
So, how are we going to judge if a particular student is really 13ics047 ??

Currently, anyone can create any no. of accounts on our app(website) and thus view other's result also.

**Comment by gargsarthak30** [comment]
I don't think we can ask for any other info. There is no unique id other than the Registration number.

**Comment by rajatsaxena035** [comment]
We can use the passwords provided by IT dept. for accessing internet.

**Comment by gargsarthak30** [comment]
First let us finalize our app and web service in this way. Once created properly, we can then talk to teachers regarding it and make changes accordingly.

**Comment by rajatsaxena035** [comment]
Fine.
