### ISSUE TITLE
Violation of the conditions of the GPL

### ISSUE THREAD

**Issue by Varun-garg** [gargsarthak30/Result-Viewer#5]
I just saw that there are 2 Result Viewer's websites. one is under OpenGbu and another is under Gautam Buddha University (http://resultviewer.esy.es) and looks more frequently updated.

A few weeks back, I was asked if my code from a project gbuonline (https://github.com/opengbu/gbuonline) could be used and I was fine with it as long as license that is included is followed. I also gave the 3 points from license that I cared about, which are as follows

```
1. The app using the code should also be open source.
2. Credits for its work should also be given to original author.
3. The files that using the code should also be under GPL.
```

In the source code at multiple places my code is used giving me credits there and saying its "logically copied". Since there was no developer's section on one at gbuonline.in/opengbu I couldn't check if condition (2) was actually followed. However on this new site (http://resultviewer.esy.es) there is a developer's section.

To honor condition 2 please also list the developers whose code that you used in the "Application UI". (Like https://www.quora.com/How-do-I-properly-credit-an-original-codes-developer-for-her-open-source-contribution). 

@rajatsaxena035 copying / "logically copying" / rewriting do not make difference to above rules, please read answer 2 of this post (https://programmers.stackexchange.com/questions/86754/is-it-possible-to-rewrite-every-line-of-an-open-source-project-in-a-slightly-dif).

Also for future purpose, according to the license

```
Part of releasing a program under the GPL is writing a copyright notice in your own name.
```

This gives original programmers veto power on their code, just in case they feel their rights being still violated. 

License or no license, it is basic courtesy that a programmer should have while including other programmer's code. Even if I didn't license it in first case, this is against at least my ethics.

**Comment by rajatsaxena035** [comment]
- Sorry to the Open-Source community.
- I was unaware of the fact (morally & legally) that I need to give credits on the Application UI for using the open-source files and software. 
- I will give acknowledgement to all the open source programs I have used in this project in the next 24 hours.
  <hr>
- Always check this GitHub repository (https://github.com/gargsarthak30/Result-Viewer) for the updated version of the project.
- The website - (http://resultviewer.esy.es) is only for temporary testing purpose. Hence it will not be updated unless we want to test any component. 
- Result-Viewer is still in the "Development Stage".
